// app/layout.tsx

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import {
    NavigationMenu,
    NavigationMenuItem,
    NavigationMenuLink,
    NavigationMenuList,
} from "@/components/ui/navigation-menu"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="bg-background text-foreground">
        <SidebarProvider>
          <div className="flex h-screen w-full">
            <AppSidebar />
            
            <div className="flex-1 flex flex-col min-w-0">
              <header className="border-b flex-shrink-0 h-16 w-full">
                <div className="h-full w-full flex items-center justify-center px-4">
                  <NavigationMenu>
                    <NavigationMenuList>
                      <NavigationMenuItem>
                        <NavigationMenuLink 
                          href="/docs/getting-started"
                          className="group inline-flex h-9 items-center justify-center 
                                     rounded-md bg-background px-4 py-2 text-sm font-medium 
                                     transition-colors hover:bg-accent hover:text-accent-foreground 
                                     focus:bg-accent focus:text-accent-foreground focus:outline-none 
                                     disabled:pointer-events-none disabled:opacity-50 
                                     data-[active]:bg-accent/50 data-[state=open]:bg-accent/50"
                        >
                          Getting Started
                        </NavigationMenuLink>
                      </NavigationMenuItem>
                      <NavigationMenuItem>
                        <NavigationMenuLink 
                          href="/about"
                          className="group inline-flex h-9 items-center justify-center 
                                     rounded-md bg-background px-4 py-2 text-sm font-medium 
                                     transition-colors hover:bg-accent hover:text-accent-foreground 
                                     focus:bg-accent focus:text-accent-foreground focus:outline-none 
                                     disabled:pointer-events-none disabled:opacity-50 
                                     data-[active]:bg-accent/50 data-[state=open]:bg-accent/50"
                        >
                          About
                        </NavigationMenuLink>
                      </NavigationMenuItem>
                    </NavigationMenuList>
                  </NavigationMenu>
                </div>
              </header>

              <main className="flex-1 overflow-auto min-w-0">
                {children}
              </main>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
